# http://module-build.sourceforge.net/META-spec.html
#
name:         URI-ftps
version:      0.02
version_from: ftps.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
